version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.8"

sphinx:
  fail_on_warning: true
  
formats:
  - pdf
  - epub
  
# Optionally declare the Python requirements required to build your docs
python:
   install:
   - requirements: docs/requirements.txt